apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://charts.pascaliske.dev
      chart: vaultwarden
      targetRevision: 0.31.0
      helm:
        valueFiles:
          - $values/values/vaultwarden-values.yaml

    - repoURL: https://github.com/FurryJulie/infra-argocd.git
      targetRevision: dev
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
